services:
  db:
    image: postgres:14.2
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data/db
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: data
      PGDATA: /var/lib/postgresql/data/db
    restart: always
  api:
    build: .
    container_name: kvartirka_api
    command: sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db
